### ISSUE TITLE
Lack of Attribution

### ISSUE THREAD

**Issue by TheKevJames** [halyard/puppet-homebrew#5]
Did you just literally copy all my code from [TheKevJames/puppet-homebrew](https://github.com/TheKevJames/puppet-homebrew) in 5b6d5094a55ec then re-release it as a version bump under your own name with no attribution? (hint: yes, yes you did).

Given my project is licensed under Apache-2.0, you should know that your project must now:
- contain a copy of or reference to the Apache-2.0 license,
- include prominent notices in all modified files stating that you changed them and their source, and
- display in some way that your MIT license does not apply to my work.

Alternatively, you could consider any or all of the following:
- asking permission before implying someone else's work as your own
- marking appropriated sections or ideas as borrowed from their owners
- contributing upstream by opening issues, submitting PRs, or joining discussions; I'm sure your project has some merit mine doesn't have and I'm sure mine has some merit yours doesn't have -- why not work together to make the best possible project rather than claiming exclusive credit for sub-optimal projects?

**Comment by akerl** [comment]
To be quite honest, I've spent the past half an hour trying to sort out how I managed this in the first place. I'm sorry for the misuse of your code; as you can see from the prior history, this repo used to be based on Boxen's puppet-homebrew, which is MIT-licensed.

It's been long enough that my memory is imperfect, but based on the commit history it seems clear that I made the decision to switch to deriving from your code when I was gutting the boxen dependencies from my provisioning, and fully missed that your project used a different license.

At the moment, I don't have the time to go through this and properly sort through the diff / attach the necessary notices, so I've yanked the Forge modules from the problem commit forward and force-reset the repo to the prior commit.

It's possible I'll go back to basing this on your code in the future, but I'll be sure to do my due diligence regarding the license. Which of course is small consolation at this point, given I didn't intend to mismanage it so badly the first time.
